// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package gosql_queries

import (
	"time"
)

type Subject struct {
	ID        string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Task struct {
	ID          string
	Description string
	State       string
	DueDate     time.Time
	SubjectID   string
	Tags        []string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
