// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package gosql_queries

import (
	"database/sql"
	"time"
)

type Subject struct {
	ID        string
	Name      string
	CreatedAt string
	UpdatedAt string
}

type Task struct {
	ID            string
	Description   string
	State         string
	DueDate       time.Time
	SubjectID     string
	IsUrgent      int64
	IsImportant   int64
	AcademicValue sql.NullFloat64
	CreatedAt     string
	UpdatedAt     string
}
